### ISSUE TITLE
Fix UI Layout bugs

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#153]
@Maurier, @jcaraballo17, @horsburgh 
I first noticed this a week or two ago while using Safari, and then it got better.
Today it's happening in Chrome. Has anyone else experience these weird layouts, which don't go away with multiple refreshes? These also don't improve when I rescale the browser window or sizing.

### Home screen, black bar is compressed to smaller than logo.

![screen shot 2018-02-05 at 3 26 44 pm](https://user-images.githubusercontent.com/5166036/35829900-ff2d0e74-0a89-11e8-96be-ee392407efc0.png)

### My Sites screen, in addition to narrow top bar, this also has a missing map and overlapping tiles. 

![screen shot 2018-02-05 at 3 27 02 pm](https://user-images.githubusercontent.com/5166036/35829910-05363318-0a8a-11e8-8908-271dcf66fe36.png)

**Comment by jcaraballo17** [comment]
@Maurier will have more insight than me on this, but try clearing your browser cache and see if it stops acting weird. 
The browser caches all stylesheets and javascript files for faster loading, and when we make a change in the html and css you can get weird stuff like this. What's strange is that we haven't pushed any style or html changes to production lately.

**Comment by Maurier** [comment]
@aufdenkampe I just tested and the same thing happened to me, but it was fixed once I cleared my cache. Not sure how it happened since we have not pushed any changes as @jcaraballo17 mentions.

**Comment by aufdenkampe** [comment]
I haven't seen this behavior in the last few days.
Not sure either how or why it happened. Each time I saw it, I refreshed the page 3 times to clear my cache for that page, and it never helped. I'll let you know when I see it again, but we can put this on back burner until it happens again.

**Comment by horsburgh** [comment]
@aufdenkampe - I'm going to close this. If it happens again we can reopen it.

**Comment by aufdenkampe** [comment]
This is happening again, on production, for Chrome only (Safari is OK). Cache clearing doesn't fix problem.

<img width="1139" alt="screen shot 2018-02-12 at 3 34 12 pm" src="https://user-images.githubusercontent.com/5166036/36120988-81858286-100a-11e8-83f7-edbda0d84ab7.png">

<img width="1137" alt="screen shot 2018-02-12 at 3 34 32 pm" src="https://user-images.githubusercontent.com/5166036/36120999-8652190a-100a-11e8-8c55-41fc311427f3.png">

<img width="1137" alt="screen shot 2018-02-12 at 3 35 00 pm" src="https://user-images.githubusercontent.com/5166036/36121003-89b6c596-100a-11e8-828c-79aa19582aa7.png">

**Comment by Maurier** [comment]
If you have this still loaded, could you post a screenshot of the browser's console?

**Comment by Maurier** [comment]
@jcaraballo17 based on the screenshots it looks like the static folder failed to be served. This seems to happen every now and then. Thoughts?

**Comment by aufdenkampe** [comment]
I'm still getting the same views in Chrome, even after refreshing the browser 3x and also following these recommendations to clear all data for these sites: http://www.thewindowsclub.com/clear-cache-cookies-specific-website

I'm happy to provide additional screenshots, but what do you mean by the browser console?

**Comment by Maurier** [comment]
The broswer's console can typically be accessed by right clicking on the page and clicking "Inspect Element" (might be something similar in your browser). It displays any errors that might have occurred.

**Comment by aufdenkampe** [comment]
@Maurier, thanks for that tip. Here are the errors from the Console.
```
/static/dataloaderinterface/css/font-awesome.min.css Failed to load resource: net::ERR_CONNECTION_REFUSED
/static/dataloaderinterface/css/style.css Failed to load resource: net::ERR_CONNECTION_REFUSED
/static/dataloaderinterface/css/home_page.css Failed to load resource: net::ERR_CONNECTION_REFUSED
/static/dataloaderinterface/js/vendor/bootstrap.min.js Failed to load resource: net::ERR_CONNECTION_REFUSED
/static/dataloaderinterface/images/site_logo.png Failed to load resource: net::ERR_CONNECTION_REFUSED
/static/dataloaderinterface/images/WikiWatershed_logo.png Failed to load resource: net::ERR_CONNECTION_REFUSED
/static/dataloaderinterface/images/creative-commons.png Failed to load resource: net::ERR_CONNECTION_REFUSED
/static/dataloaderinterface/images/section_image_1.jpg Failed to load resource: net::ERR_CONNECTION_REFUSED
/static/dataloaderinterface/js/vendor/parallax.min.js Failed to load resource: net::ERR_CONNECTION_REFUSED
/static/dataloaderinterface/images/logo_stroud.png Failed to load resource: net::ERR_CONNECTION_REFUSED
```

**Comment by Maurier** [comment]
@jcaraballo17 this looks like a server configuration problem.

**Comment by jcaraballo17** [comment]
Closing.
