### ISSUE TITLE
WebTSA showing wrong variable for new sites

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#284]
@horsburgh, @Maurier @jcaraballo17.

@gcutrell and I just noticed a new bug on WebTSA for the new sites he set up.

For http://data.envirodiy.org/sites/MeteoTsu-2/, clicking on WebTSA button for any variable, such as battery voltage, http://data.envirodiy.org/tsa/?sitecode=MeteoTsu-2&variablecode=EnviroDIY_Mayfly_Batt&view=visualization&plot=true, only shows the first variable (pressure).

Same is true for http://data.envirodiy.org/sites/MeteoTsu-3/ and http://data.envirodiy.org/tsa/?sitecode=MeteoTsu-3&variablecode=EnviroDIY_Mayfly_Batt&view=visualization&plot=true

I created this station about a month earlier, before the latest release. It is otherwise identical, but not exhibiting the same behavior. http://data.envirodiy.org/sites/MeteoTsu-1/ and http://data.envirodiy.org/tsa/?sitecode=MeteoTsu-1&variablecode=EnviroDIY_Mayfly_Batt&view=visualization&plot=true

I *think* that this wasn't an issue just yesterday when we were viewing battery voltage. Were there any changes to production that might have introduced this bug in the last 24 hours?

**Comment by Maurier** [comment]
There have not been any changes, but I'll investigate further.

**Comment by aufdenkampe** [comment]
Any updates on this issue?

@fisherba noticed the same behavior for her 2 new stations:
- http://data.envirodiy.org/sites/WSP01/
- http://data.envirodiy.org/sites/WSP02/

She writes:

> When we try to look at Time Series Analyst for the temperature profile on these sites, it only displays the time series data for Gage Height. And the Gage Height time series is also buggy because it lists 5 instances of that variable in the legend.

**Comment by horsburgh** [comment]
Update - @jcaraballo17 is looking at this. It looks like an issue with the catalog database that is used by the TSA to populate its forms. Working on it.

**Comment by horsburgh** [comment]
The original issue has been resolved by a rebuild of the catalog database for TSA. 

There is still a minor issue where if you have multiple of the exact same sensor measuring the exact same variable at the same site. If you click on the TSA link for any one of these time series you get them all in the plot in TSA. This affects the two sites mentioned two comments above:

http://data.envirodiy.org/sites/WSP01/
http://data.envirodiy.org/sites/WSP02/

This is a different issue than the one listed here and so I'm going to add the "tested" label for the purposes of this release. @jcaraballo17 - is looking into what it will take to more explicitly address each time series. This is an artifact of our original implementation that was based on time series coming from an ODM 1.1 database. The URL that gets constructed uses the SiteCode and VariableCode to launch TSA, but in the new implementation, those two parameters are not enough to identify a single time series when there is more than one time series for a sensor/variable at the same site.

**Comment by aufdenkampe** [comment]
Thanks! It looks good on production!

**Comment by horsburgh** [comment]
Live on production. Closing.

**Comment by aufdenkampe** [comment]
I just noticed this bug is still occurring for these related stations that were not explicitly named above:
- https://data.envirodiy.org/sites/MeteoTsu-4/ & http://data.envirodiy.org/tsa/?sitecode=MeteoTsu-4&variablecode=EnviroDIY_Mayfly_Batt&view=visualization&plot=true
- https://data.envirodiy.org/sites/MeteoTsu-5/ & http://data.envirodiy.org/tsa/?sitecode=MeteoTsu-5&variablecode=EnviroDIY_Mayfly_Batt&view=visualization&plot=true

Is there a way to fix this holistically, so that we don't need to "test" each station that was created this summer?

**Comment by aufdenkampe** [comment]
Also true for true for http://data.envirodiy.org/sites/MeteoTsu-3/ and http://data.envirodiy.org/tsa/?sitecode=MeteoTsu-3&variablecode=EnviroDIY_Mayfly_Batt&view=visualization&plot=true.

This station was mentioned above and I think I checked that it was fixed, but I'm not certain of that.

**Comment by horsburgh** [comment]
@aufdenkampe - I spoke with @jcaraballo17 briefly about this yesterday. We thought we had this fixed, but apparently something is still going haywire. Juan's got some thoughts about how this needs to be addressed, but it doesn't look like a super trivial effort. 

There is a way to regenerate the catalog database that is used by TSA, but the bug is in the automated syncing/updating of sites/variables with that database. So, even though a regeneration of the catalog database would likely temporarily fix this, as new sites/variables are created things will get out of sync again because of the bug with the automated procedure.

**Comment by aufdenkampe** [comment]
Thanks for the update. Do you think you can find a way to fix it? You could use Monitor MW funds if that is a constraint.

**Comment by aufdenkampe** [comment]
@horsburgh and @jcaraballo17, it seems that the reemergence of this issue is quite widespread, and potentially getting worse (or I hadn't noticed how widespread it was on Friday). In short, it seems that WebTSA is not very functional.

@SRGDamia1, @darscott and @fisherba, do you notice similar issues at your sites?

**Comment by horsburgh** [comment]
@jcaraballo17 - how can I test this?

**Comment by aufdenkampe** [comment]
This issue just reappeared in our workshop just now, for a new user at a new site.
http://data.envirodiy.org/sites/test/

Given the site name, could this be an issue with data from a deleted site?

**Comment by aufdenkampe** [comment]
Also for another new user at a different site.
http://data.envirodiy.org/sites/test0/

Clicking on view in TSA for any variables leads to only be able to view `EnviroDIY_Mayfly_Batt: Battery voltage`

**Comment by SRGDamia1** [comment]
I'm seeing this too, for new variables added at an old site.

**Comment by jcaraballo17** [comment]
I'll take a look at this tomorrow. In the meantime I'm going to rebuild the TSA catalog with the correct series after you're done with your workshop.

**Comment by aufdenkampe** [comment]
@jcaraballo17, thanks for looking into this. My workshop was just 1-day, so please move forward with this.

**Comment by aufdenkampe** [comment]
@jcaraballo17, we'll also want to fix this as a hot fix ASAP.
Also similar to #342, it will be important for you to describe the bug and its fix to @steveskrip, @htaolimno and me, so that we can avoid these kinds of bugs in the future.

**Comment by horsburgh** [comment]
@aufdenkampe - with only about a month left on our existing contract, it might be good to get the LimnoTech guys more involved with the coding if you are really going to take over hosing of the Data Sharing Portal. Any chance you guys could help fix some of these issues?

**Comment by jcaraballo17** [comment]
Closing. Not using the script that caused this anymore.

**Comment by aufdenkampe** [comment]
@jcaraballo17, can you point to the new script (using a GitHub URL) and the old script it is replacing, and perhaps also the relevant commits?

I would like to have the fix well-documented.

**Comment by jcaraballo17** [comment]
@aufdenkampe Django scripts go on the `management/commands` directory of the app. In this case the script is in `dataloaderinterface/management/commands` and it's called  [`generate_influx_data.py`](https://github.com/ODM2/ODM2DataSharingPortal/blob/development/src/dataloaderinterface/management/commands/generate_influx_data.py).
The script it replaced is not in this repository. It's part of a set of tools for the TSA, and can be found [here](https://github.com/UCHIC/webtsa-utilities/blob/master/src/EnviroDIYRunner.py).
And the new script was part of commit   https://github.com/ODM2/ODM2DataSharingPortal/commit/e2b80ba146558be34d8b7c2064d179fc4cc52243.

**Comment by aufdenkampe** [comment]
Thank you!
