### ISSUE TITLE
Fix broken "Add New Sensor" for some variables

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#342]
While teaching a group today, we all got errors and couldn't move forward when trying to add specific variables, including:
* Bosch_BME280_Temp
* Maxim_DS18BB20_Temp

Maybe there are others?

@jcaraballo17, @Maurier, any idea what might be happening? Is this a database issue related to the migration, similar to what we've seen previously?

cc: @horsburgh, @SRGDamia1

**Comment by jcaraballo17** [comment]
Can't think of any reason that would happen. 
I'll take a look at it and try to figure out what the issue is in a bit.

**Comment by horsburgh** [comment]
@aufdenkampe - can you describe the steps and the specific error?

**Comment by horsburgh** [comment]
I just tried to add these two sensors to one of my sites, and when I click the button to add them I just get a small message at the bottom that says "Failed to add sensor" and it just leaves me in the modal window. @aufdenkampe - have you had issues with any others?

**Comment by SRGDamia1** [comment]
I got it yesterday with a Zebra Tech DO in ppm, though, oddly, not the other DO variable..

**Comment by jcaraballo17** [comment]
I figured out what the problem is, I'll try to fix it tomorrow or the beginning of next week. Do we want to create a hotfix for this one? I don't think we should wait until the next release to fix this bug.

**Comment by SRGDamia1** [comment]
Please, please fix this ASAP!

**Comment by aufdenkampe** [comment]
@horsburgh and @SRGDamia1, thanks for digging in and providing extra details.

@jcaraballo17, thanks for figuring out the problem. Please fix this as a hot fix as soon as possible, as it is a big bug that stops us from deploying new stations (which we're still doing this winter).

Once you get it fixed, it will be important for you to describe the bug to @steveskrip, @htaolimno and me, so that we can avoid these kinds of bugs in the future.

**Comment by SRGDamia1** [comment]
@aufdenkampe - You can set up the station with the wrong variable and then go back and change the variable metadata that's tied to that UUID once this problem is fixed.  It's a PITA though.

**Comment by jcaraballo17** [comment]
@aufdenkampe @SRGDamia1 Fixed!

**Comment by aufdenkampe** [comment]
@gcutrell, @fisherba, and I all just discovered that this bug has again appeared for at least this sensor:
* Maxim_DS18BB20_Temp

It seems to work, however, for the `Bosch_BME280_Temp` sensor.

@jcaraballo17, is there anything else that you did with the databases records to fix this? It seems that the code fix #342 would not have caused or fixed the problem alone, given that it was only for a few of the sensors. It would be very helpful to describe what you might have done with the database records to fix this.

**Comment by dbressler75** [comment]
Ensign and I had the same/similar problem recently.  Decagon CTD depth and conductivity could be added but not add Decagon CTD temp - "Failed to add new sensor"

**Comment by dbressler75** [comment]
Time offset issue - no UUID for time offset when uploading new data/new sensors.  No instructions in current manual for how to deal with Time offset and any UUID that may be necessary for this parameter

**Comment by dbressler75** [comment]
Seemingly all new sensor additions/data uploads give the message "Failed to upload"; however, data actually do upload (for particular sensors, but not others - see previous comments)

**Comment by aufdenkampe** [comment]
@dbressler75, thanks for providing additional input on this issue. we'll add `Decagon CTD temp` to the list of sensor/variables that are somehow unlinked from the database.

Regarding Time offset, that is timezone information that when added to the local date time value allows one to convert between timezones. Therefore, there is no need for a UUID. UUIDs are only given to measured sensor variables, and also as unique identifies for sites (which are a type of Sampling Feature, according to the conventions of the Open Geospatial Consortium's Observations and Measurements standard).

**Comment by SRGDamia1** [comment]
Is there any chance this will be fixed?

**Comment by aufdenkampe** [comment]
Yes! We just received a bit of funding and will get started in the next few days.

Sent from my iPhone

On Apr 24, 2019, at 5:48 PM, Sara Damiano <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there any chance this will be fixed?

-

**Comment by SRGDamia1** [comment]
Oh, thank goodness!

**Comment by aufdenkampe** [comment]
@gcutrell has been having this bug with adding these sensor variables:
- Davis_VantagePro2_5minRainTotal
- Davis_VantagePro2_15minRainTotal

But it works with:
- Davis_VantagePro2_10minRainTotal

@jcaraballo17 and @htaolimno, I think this could be potential database issue.

**Comment by aufdenkampe** [comment]
For https://monitormywatershed.org/sites/RVSMRT%232/ we want `Davis_VantagePro2_5minRainTotal` in inches, so I tried @SRGDamia1's suggested workaround (see https://github.com/ODM2/ODM2DataSharingPortal/issues/342#issuecomment-447498516) and decided to temporarily set up the station with `Davis_VantagePro2_10minRainTotal`. However, I wanted units of inches, but after adding that as an `instrument output variable` via the Django Admin panel, I now get a `Failed to update sensor` error when I select:
- Davis_VantagePro2_10minRainTotal, in *inches*

cc: @Volk3rJ

**Comment by aufdenkampe** [comment]
Fixed with https://github.com/ODM2/ODM2DataSharingPortal/commit/298bc70093bf90773708e7f221fae8db4baebf35, which is in the Master branch. We'll try a hot-fix.

**Comment by jcaraballo17** [comment]
Fixed.
- Updated the server with the latest master branch code with the december hotfix.
- Ran a `collectstatic` command to update the modified javascript file on the static folder.

**Comment by fisherba** [comment]
I just tested and the sensors I couldn't add yesterday worked today (all were the temp variable for each sensor). Thanks!

**Comment by jcaraballo17** [comment]
Perfect!
Adding the `close me` tag.

**Comment by aufdenkampe** [comment]
These sensor/variables still do not work:
- `Decagon_CTD-10_Temp`
- `Maxim_DS18B20_Temp`, which was the sensor/variable originally listed in this issue.

@fisherba said she had to log out and then log back in, but that didn't work for me. I'm about to try a different browser.

**Comment by aufdenkampe** [comment]
@fisherba and I just did some extensive testing, and what we found was that there is a very persistent caching situation, where it all worked when we each when to a browser that we haven't recently used.

However, for the browser we each most often use (Safari for me, Chrome for Beth), no amount of refreshing the browser, restarting the browser, or logging out would solve the issue.

I'll try again in a few days.

**Comment by aufdenkampe** [comment]
From @Volk3rJ:

> I had luck with adding new sensors after clearing all my browsing data in Chrome (for the last hour – incl. history, cookies and cache). I had to do this for each sensor I wanted to add.

I just did a hard "Empty Caches" command in Safari, and finally got it to work. I'm surprised that the softer cache reseting of refreshing the browser there times didn't work.

**Comment by aufdenkampe** [comment]
This should be permanently fixed with:
- #529
